"""Agregar tablas de cursos, inscripciones, examenes, preguntas, actividades y resultados

Revision ID: 0886727ce1d6
Revises: 3b244fcec702
Create Date: 2025-06-29 13:39:27.848797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0886727ce1d6'
down_revision = '3b244fcec702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('objetivo', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('area_tematica', sa.String(length=100), nullable=False),
    sa.Column('duracion', sa.String(length=50), nullable=False),
    sa.Column('tipo_agente', sa.String(length=50), nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.DateTime(), nullable=True),
    sa.Column('avance', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividad_resultados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inscripcion_id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('entregado', sa.Boolean(), nullable=True),
    sa.Column('fecha_entregado', sa.DateTime(), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('retroalimentacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examen_resultados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inscripcion_id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('fecha_realizado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('opciones', sa.Text(), nullable=True),
    sa.Column('respuesta_correcta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preguntas')
    op.drop_table('examen_resultados')
    op.drop_table('actividad_resultados')
    op.drop_table('inscripciones')
    op.drop_table('examenes')
    op.drop_table('actividades')
    op.drop_table('cursos')
    # ### end Alembic commands ###
