"""Agregar campo video_url a Actividad

Revision ID: 115b12b5170f
Revises: 3873e878476f
Create Date: 2025-07-04 20:38:23.139132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115b12b5170f'
down_revision = '3873e878476f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_fecha_carga'), ['fecha_carga'], unique=False)

    with op.batch_alter_table('logros', schema=None) as batch_op:
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logros', schema=None) as batch_op:
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_fecha_carga'))
        batch_op.drop_index(batch_op.f('ix_documentos_categoria'))

    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
