"""Add project visibility to posts

Revision ID: 252fc144b630
Revises: 87d781030370
Create Date: 2025-07-20 09:26:46.432183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252fc144b630'
down_revision = '87d781030370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_proyectos',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'proyecto_id')
    )
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_cursos_categoria_id', 'categorias', ['categoria_id'], ['id'])
        batch_op.drop_column('categoria')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_para_todos', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('visible_para_todos')

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_cursos_categoria_id', type_='foreignkey')
        batch_op.drop_column('categoria_id')

    op.drop_table('post_proyectos')
    # ### end Alembic commands ###
