"""Inicial

Revision ID: acf8b5e530d1
Revises: 
Create Date: 2025-06-23 16:45:26.803710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf8b5e530d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('documentos_probatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('entidades_federativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estatus_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('instituciones_educativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('niveles_estudios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ocupaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('puestos_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('entidad_federativa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entidad_federativa_id'], ['entidades_federativas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estatus_id', sa.Integer(), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=50), nullable=False),
    sa.Column('apellido_materno', sa.String(length=50), nullable=True),
    sa.Column('curp', sa.String(length=18), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('puesto_trabajo_id', sa.Integer(), nullable=True),
    sa.Column('jefe_inmediato_id', sa.Integer(), nullable=True),
    sa.Column('ocupacion_especifica_id', sa.Integer(), nullable=True),
    sa.Column('institucion_educativa_id', sa.Integer(), nullable=True),
    sa.Column('nivel_max_estudios_id', sa.Integer(), nullable=True),
    sa.Column('documento_probatorio_id', sa.Integer(), nullable=True),
    sa.Column('entidad_federativa_id', sa.Integer(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['documento_probatorio_id'], ['documentos_probatorios.id'], ),
    sa.ForeignKeyConstraint(['entidad_federativa_id'], ['entidades_federativas.id'], ),
    sa.ForeignKeyConstraint(['estatus_id'], ['estatus_usuarios.id'], ),
    sa.ForeignKeyConstraint(['institucion_educativa_id'], ['instituciones_educativas.id'], ),
    sa.ForeignKeyConstraint(['jefe_inmediato_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.ForeignKeyConstraint(['nivel_max_estudios_id'], ['niveles_estudios.id'], ),
    sa.ForeignKeyConstraint(['ocupacion_especifica_id'], ['ocupaciones.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['puesto_trabajo_id'], ['puestos_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curp'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('municipios')
    op.drop_table('puestos_trabajo')
    op.drop_table('proyectos')
    op.drop_table('ocupaciones')
    op.drop_table('niveles_estudios')
    op.drop_table('instituciones_educativas')
    op.drop_table('estatus_usuarios')
    op.drop_table('entidades_federativas')
    op.drop_table('documentos_probatorios')
    op.drop_table('departamentos')
    # ### end Alembic commands ###
