"""Agregar campo type con default a Reaction

Revision ID: b57672436f3b
Revises: 66786ba67867
Create Date: 2025-06-26 10:11:24.875971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57672436f3b'
down_revision = '66786ba67867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=False, server_default='love'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
