"""Crear tabla documentos

Revision ID: be6413130d0e
Revises: b57672436f3b
Create Date: 2025-06-29 04:32:54.172821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6413130d0e'
down_revision = 'b57672436f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('archivo', sa.String(length=200), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos')
    # ### end Alembic commands ###
