"""Creación de tabla tickets

Revision ID: cace3f458c3b
Revises: be6413130d0e
Create Date: 2025-06-29 11:33:41.109141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cace3f458c3b'
down_revision = 'be6413130d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('estatus', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aprobaciones_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estatus', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('aprobador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aprobador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('emisor_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emisor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios_ticket')
    op.drop_table('aprobaciones_ticket')
    op.drop_table('tickets')
    # ### end Alembic commands ###
