"""agregar campo reportado a tickets

Revision ID: e8f2a9d4b1c5
Revises: d27c4aae1602
Create Date: 2025-07-23 18:43:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f2a9d4b1c5'
down_revision = 'd27c4aae1602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reportado', sa.Boolean(), nullable=True))
    
    # Establecer valores por defecto para registros existentes
    op.execute("UPDATE tickets SET reportado = 0 WHERE reportado IS NULL")
    
    # Hacer la columna no nullable después de establecer valores por defecto
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('reportado', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('reportado')
    # ### end Alembic commands ###